name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Only macOS and Windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # - name: Install dependencies (macOS)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew update
    #     brew install llvm make

    # - name: Install dependencies (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     choco install llvm make mingw
    #     echo "C:\Program Files\LLVM\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
    #     echo "C:\ProgramData\chocolatey\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

    - name: Verify Clang installation (Windows)
      if: runner.os == 'Windows'
      run: clang --version

    - name: Build
      run: go build interpreter.go

    # - name: Test
      # run: go test -v ./...
