on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build the binary for macOS
      run: |
        mkdir -p release
        GOOS=darwin GOARCH=arm64 go build -o release/turtle-darwin-arm64

    - name: Create macOS Installer
      run: |
        mkdir -p pkgroot/usr/local/bin
        cp release/turtle-darwin-arm64 pkgroot/usr/local/bin/turtle
        chmod 755 pkgroot/usr/local/bin/turtle
        pkgbuild --root pkgroot --identifier com.genesys.turtle \
          --version 0.1.6 --install-location /usr/local/bin \
          --ownership recommended release/turtle.pkg

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.1.6
        files: release/turtle.pkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build the binary for Linux
      run: |
        mkdir -p release
        GOOS=linux GOARCH=amd64 go build -o release/turtle-linux-amd64

    - name: Install fpm for packaging
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev
        sudo gem install --no-document fpm

    - name: Create Linux Installer
      run: |
        fpm -s dir -t deb -n turtle -v 0.1.6 --prefix /usr/local/bin -C release .
        mv turtle_0.1.6_amd64.deb release/turtle-linux-amd64.deb

    - name: Upload Linux Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.1.6
        files: release/turtle-linux-amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build the binary for Windows
      run: |
        mkdir -p release
        $env:GOOS="windows"
        $env:GOARCH="amd64"
        go build -o release/turtle-windows-amd64.exe

    - name: Upload Windows Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.1.6
        files: release/turtle-windows-amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
