name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]  # macOS, Windows, and Linux (Ubuntu)

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Install Clang (Windows)
    - name: Install Clang (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install llvm
        echo "C:\Program Files\LLVM\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

    - name: Verify Clang installation (Windows)
      if: runner.os == 'Windows'
      run: clang --version

    # Install dependencies (Linux)
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang

    # Set fallback version
    - name: Set fallback version
      run: echo "VERSION=v0.0.0" >> $GITHUB_ENV  # You can change this to any default version you prefer

    # Build the project with the fallback version
    - name: Build
      run: go build -o interpreter-${{ env.VERSION }}.exe interpreter.go

    # Ensure the release directory exists before moving the files
    - name: Ensure release directory exists
      run: mkdir -p ./release

    # Move the built file to the release directory
    - name: Move build artifact to release directory
      run: mv interpreter-${{ env.VERSION }}.exe ./release/interpreter-${{ matrix.os }}-${{ env.VERSION }}

    # Create GitHub Release and Publish Binaries
    - name: Publish Binaries to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
